// src/main/java/com/_Y2_S1_MTR_02/dto/TrainScheduleDTO.java
package _Y2_S1_MTR_02.dto;

import com.slraile.model.TrainType;
import com.slraile.model.TrainStatus;

public class TrainScheduleDTO {

    private Long id;
    private String trainName;
    private TrainType trainType;
    private String routeFrom;
    private String routeTo;
    private String departureTime; // HH:mm
    private String arrivalTime;   // HH:mm
    private Integer platform;
    private TrainStatus status;
    private Double economyPrice;
    private Double businessPrice;
    private Double firstPrice;
    private String notes;
    private String duration; // calculated
    private String priceDisplay; // calculated

    // Constructors
    public TrainScheduleDTO() {}

    public TrainScheduleDTO(Long id, String trainName, TrainType trainType, String routeFrom, String routeTo,
                            String departureTime, String arrivalTime, Integer platform, TrainStatus status,
                            Double economyPrice, Double businessPrice, Double firstPrice, String notes,
                            String duration, String priceDisplay) {
        this.id = id;
        this.trainName = trainName;
        this.trainType = trainType;
        this.routeFrom = routeFrom;
        this.routeTo = routeTo;
        this.departureTime = departureTime;
        this.arrivalTime = arrivalTime;
        this.platform = platform;
        this.status = status;
        this.economyPrice = economyPrice;
        this.businessPrice = businessPrice;
        this.firstPrice = firstPrice;
        this.notes = notes;
        this.duration = duration;
        this.priceDisplay = priceDisplay;
    }

    // Getters and Setters (Lombok can generate these)
    // ... (generated by IDE or Lombok)
}